sudo: false

language: node_js
node_js:
  - "0.10"
  - "0.12"

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - export PATH="$HOME/.meteor:$PATH"

script: "meteor --test --release velocity:METEOR@1.1.0.2_3"